version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
